telegraf_global_tags: []

telegraf_outputs: []
#telegraf_outputs:
#  - type: influxdb
#    config:
#      - urls = ["http://127.0.0.1:8086"]
#      - database = ""
#      - exclude_database_tag = true
#      - username = ""
#      - password = ""

telegraf_inputs_default:
  - type: cpu
    config:
      - percpu = true
      - totalcpu = true
      - collect_cpu_time = false
      - report_active = false
  - type: disk
    config:
      - ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
      - fieldpass = ["used_percent", "total"]
  - type: internal
    config:
      - collect_memstats = false
      - tagexclude = ["go_version", "version"]
      - namedrop = ["internal_statsd"]
  - type: mem
    config:
      - fieldpass = ["used_percent", "total"]
  - type: statsd
    config:
      - protocol = "udp"
      - tcp_keep_alive = false
      - service_address = ":8125"
      - delete_gauges = true
      - delete_counters = true
      - delete_sets = true
      - delete_timings = true
      - percentiles = [90.0]
      - metric_separator = "."
      - parse_data_dog_tags = false
      - datadog_extensions = false
      - allowed_pending_messages = 10000
      - percentile_limit = 1000
      - tagexclude = ["metric_type"]
      - fielddrop = ["count", "stddev", "sum"]

telegraf_inputs_extra: []
#telegraf_inputs_extra:
#  - type: nginx_vts
#    config:
#      - urls = ["http://localhost/_nginx_status/format/json"]
